name: CI

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: docker/login-action@v3
        with:
          username: nitzan12
          password: ${{ secrets.DOCKER_TOKEN }}

      - run: |
          VERSION="1.0.$((GITHUB_RUN_NUMBER - 1))"

          docker build \
            --build-arg VERSION=$VERSION \
            -t nitzan12/simple-java-maven-app:$VERSION \
            .

          docker push nitzan12/simple-java-maven-app:$VERSION
