name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: nitzan12
          password: ${{ secrets.DOCKER_TOKEN }}

      - run: |
          VERSION="1.0.$((GITHUB_RUN_NUMBER - 1))"

          docker build \
            --build-arg VERSION=$VERSION \
            -t nitzan12/simple-java-maven-app:$VERSION \
            .

          docker push nitzan12/simple-java-maven-app:$VERSION
